name: Run Tests
on: [push, pull_request]
jobs:
  run-pg-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres_version: [
          "9-alpine",
          "10-alpine",
          "11-alpine",
          "12-alpine",
          "13-alpine"
        ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build & test postgres
        env:
          PG_IMAGE_VERSION: ${{ matrix.postgres_version }}

        run: |
          cd ${{ github.workspace }}
          make build
          make up
          make test-pg
          make down

  run-mysql-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mysql_version: [
          "8-alpine"
        ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build & test mysql
        env:
          MYSQL_VERSION: ${{ matrix.mysql_version }}

        run: |
          cd ${{ github.workspace }}
          make build
          make up
          make test-mysql
          make down

  run-mssql-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mssql_version: [
          "2017-latest", "2019-latest"
        ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build & test mssql
        env:
          MSSQL_VERSION: ${{ matrix.mssql_version }}

        run: |
          cd ${{ github.workspace }}
          make build
          make up
          make test-mssql
          make down

  run-sqlite-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build & test sqlite
        run: |
          cd ${{ github.workspace }}
          make build
          make up
          make test-sqlite
          make down
